export { default as MenuOption } from './MenuOption.vue'
export { default as ContactForm } from './ContactForm.vue'
export { default as PlacesSlide } from './PlacesSlide.vue'
export { default as Collapse } from './Collapse.vue'
export { default as PlaceSlide } from './PlaceSlide.vue'
export { default as PlaceTitle } from './PlaceTitle.vue'
